spring:
  datasource:
    url: "jdbc:mysql://sopkathon-database.czk6okg68de0.ap-northeast-2.rds.amazonaws.com/sopkathon"
    username: "admin"
    password: "sopkathon1234"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
