name: CI

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-22.04 

    steps: 
    - name: 체크아웃
      uses: actions/checkout@v3

    - name: JDK 17 설치
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: application.yml 생성
      run: | 
        mkdir -p src/main/resources
        echo "${{ secrets.APPLICATION }}" > src/main/resources/application.yml

    - name: Gradle 빌드
      run: |
        chmod +x ./gradlew
        ./gradlew build -x test
      shell: bash
